name: Cleanup Registry

on:
  schedule:
    - cron: "42 10 * * *"
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        type: boolean
        required: true
        default: false

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    concurrency:
      group: repo-${{ github.repository }}-registry # Do not run in parallel!
    steps:
      - name: Get Package Name
        id: package-name
        env:
          GH_REPO_AND_OWNER: ${{ github.repository }}
        run: echo "package-name=$(echo "${GH_REPO_AND_OWNER}" | cut -d'/' -f2)" >> "${GITHUB_OUTPUT}"
      - uses: dataaxiom/ghcr-cleanup-action@v1.2.1
        with:
          package: ${{ steps.package-name.outputs.package-name }}
          delete-untagged: "true"
          delete-ghost-images: "true"
          delete-partial-images: "true"
          delete-orphaned-images: "true"
          validate: "true"
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run }}
          token: ${{ github.token }}
      # This action currently messes up multiarch images:
      # https://github.com/actions/delete-package-versions/issues/90
      # - uses: actions/delete-package-versions@v5
      #   with:
      #     package-name: ${{ steps.package-name.outputs.package-name }}
      #     package-type: container
      #     min-versions-to-keep: 10
      #     delete-only-untagged-versions: 'true'
